[tool.black]
target-version = ['py310']
include = '\.pyi?$'
exclude = '''
/(
    \.git
  | \.mypy_cache
  | \.pytest_cache
  | \.venv
  | \.tox
  | build
  | dist
)/
'''

[tool.isort]
profile = "black"
known_first_party = "src"
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
combine_as_imports = true

[tool.pytest.ini_options]
testpaths = ["tests"]
minversion = "6.0"
addopts = "--strict-markers --tb=short --disable-warnings"

[tool.pylint]
disable = [
    "C0114",  # Missing module docstring
    "C0116",  # Missing function or method docstring
    "R0903",  # Too few public methods in class
]
